# fly.toml file generated for atreus-worker on 2021-07-05T15:19:02+07:00

app = "atreus-worker"

kill_signal = "SIGINT"
kill_timeout = 5

[processes]
worker = "./worker"

[experimental]
  allowed_public_ports = []
  auto_rollback = false
