# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build-dasboard:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          run_install: |
            - cwd: ./dashboard
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Install Dependencies
        working-directory: ./dashboard
        run: pnpm install
      - name: Build
        working-directory: ./dashboard
        run: yarn build
